"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup, find_packages
import budget

PACKAGES = ['sqlalchemy.dialects.sqlite']
MODULES = ['sqlite3']
includes = ["sqlalchemy.databases.sqlite"]


APP = ['budget/budgetManager.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
           'packages': PACKAGES,
           'iconfile': 'appIcon.icns',
           'includes': ['sqlalchemy.dialects.sqlite']}

setup(
    name='BudgetManager',
    version=budget.__version__,
    description='An application that keeps track of your budget (expenses)',
    app=APP,
    author='Deep Aggarwal',
    author_email='deep.uiuc@gmail.com',
    maintainer='Deep Aggarwal',
    maintainer_email='deep.uiuc@gmail.com',
    data_files=DATA_FILES,
    include_package_data=True,
    packages=find_packages(),
    options={'py2app': OPTIONS},
    setup_requires=['py2app', "sqlalchemy"]
)
