"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup, find_packages

PACKAGES = ['sqlalchemy.dialects.sqlite']
MODULES = ['sqlite3']
includes = ["sqlalchemy.databases.sqlite"]


APP = ['budget/budgetManager.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

OPTIONS = {'argv_emulation': True,
           'packages': PACKAGES,
           'includes' : ['sqlalchemy.dialects.sqlite']}

setup(
    app=APP,
    data_files=DATA_FILES,
    include_package_data=True,
    packages=find_packages(),
    options={'py2app': OPTIONS},
    setup_requires=['py2app', "sqlalchemy"]
)
